### ISSUE TITLE
Getapps(china Ver.) Bug in MIUI 14

### ISSUE THREAD

**Issue by white44water** [AndroPlus-org/magisk-module-miui-cn2global-lite#1]
mix fold2 Miui stable 14.0.3
when magisk-module-miui-cn2global-lite  active
Getapps(china Ver.) cannot download/update any apps

**Comment by AndroPlus-org** [comment]
GetApps is made for China ROM but this module changes the flag to Global, so MIUI disables functionality of GetApps.
This can't be bypassed with this module.
Maybe creating Zygsik or Xposed module can fix it, but I have no plan to do it.
